=== gajarajkalburgi/spring-integration/core/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "assert": {
          "type": "object",
          "properties": {
            "body": {
              "enum" : ["EQUALS","SCHEMA","IGNORE","REGEX"]
            },
            "header": {
              "enum" : ["EQUALS","REGEX"]
            },
            "ignore": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            },
            "order": {
              "type": "boolean"
            },
            "swagger": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "properties": {
          "type": "object"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "description"
      ]
    },
    "setup": {
      "type": "object",
      "properties": {
        "database": {
          "type": ["object", "array"]
        },
        "wiremock": {
          "type": ["object", "array"]
        },
        "mongodb": {
          "type": ["object", "array"]
        },
        "amqp": {
          "type": ["object", "array"],
          "properties": {
            "queue": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "exclusive": {
                  "type": "boolean",
                  "default": false
                },
                "autoDelete": {
                  "type": "boolean",
                  "default": false
                },
                "arguments": {
                  "type": "object"
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            },
            "exchange": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "type": {
                  "enum": ["direct", "fanout", "topic", "headers", "DIRECT", "FANOUT", "TOPIC", "HEADERS"],
                  "default": "fanout"
                },
                "routingKey": {
                  "type": "string"
                },
                "autoDelete": {
                  "type": "boolean",
                  "default": false
                },
                "arguments": {
                  "type": "object"
                },
                "headers": {
                  "type": ["object", "string", "array"]
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            },
            "messages": {
              "type": ["object", "string", "array"]
            }
          },
          "additionalProperties": false,
          "required": ["queue", "exchange"]
        }
      },
      "additionalProperties": false
    },
    "request": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "minLength": 1
        },
        "method": {
          "enum": ["GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"]
        },
        "headers": {
          "type": ["object", "string"]
        },
        "body": {
          "type": ["object", "array", "string", "null"]
        },
        "query": {
          "type": ["object", "null"]
        },
        "path": {
          "type": ["array", "null"]
        }
      },
      "additionalProperties": false,
      "required": [
        "url",
        "method"
      ]
    },
    "response": {
      "type": "object",
      "properties": {
        "status": {
          "type": "number",
          "minimum": 200,
          "maximum": 510
        },
        "headers": {
          "type": ["object","string"]
        },
        "body": {
          "type": ["object", "array", "string", "null", "boolean", "integer", "number"]
        }
      },
      "additionalProperties": false,
      "required": [
        "status"
      ]
    },
    "scenario": {
      "type": "array",
      "properties": {
        "request": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "minLength": 1
            },
            "method": {
              "enum": ["GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"]
            },
            "headers": {
              "type": ["object", "string"]
            },
            "body": {
              "type": ["object", "array", "string", "null"]
            }
          },
          "additionalProperties": false,
          "required": [
            "url",
            "method"
          ]
        },
        "response": {
          "type": "object",
          "properties": {
            "status": {
              "type": "number",
              "minimum": 200,
              "maximum": 510
            },
            "headers": {
              "type": ["object","string"]
            },
            "body": {
              "type": ["object", "array", "string", "null", "boolean", "integer", "number"]
            }
          },
          "additionalProperties": false,
          "required": [
            "request",
            "response"
          ]
        }
      }
    },
    "cleanup": {
      "type": "object",
      "properties": {
        "database": {
          "type": ["object", "array"]
        },
        "mongodb": {
          "type": ["object", "array"]
        },
        "amqp": {
          "type": ["object", "array"],
          "properties": {
            "queue": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            },
            "exchange": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "oneOf" : [
    {
      "required": [
        "metadata",
        "request",
        "response"
      ]
    },
    {
      "required": [
        "metadata",
        "scenario"
      ]
    }
  ]
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/media/AssertPdf.json
{
  "metadata": {
    "name": "Assert PDF",
    "description": "Assert PDF"
  },
  "setup": {
  },
  "request": {
    "url": "/media/",
    "method": "GET",
    "headers": {
      "Accept": "application/pdf"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/pdf"
    },
    "body": "@media/spoke.pdf"
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/AssertMultiple.json
{
  "metadata": {
    "name": "Assert multiple request and response",
    "description": "multiple request and response",
    "assert": {
      "header": "REGEX",
      "ignore": [
        "$._links"
      ]
    },
    "properties": {
      "firstName": "FOO",
      "lastName": "BAR",
      "newFirstName": "HOGE",
      "newLastName": "PIYO"
    }
  },
  "setup": {
  },
  "scenario": [
    {
      "request": {
        "url": "/api/core-test",
        "method": "POST",
        "body": {
          "flag": true,
          "amt": 100,
          "desc": "foo"
        }
      },
      "response": {
        "status": 201,
        "headers": {
          "Content-Type": {
            "$ref": "integration/constant.json/#/contentType/applicationJson"
          }
        },
        "body": {
          "flag": true,
          "amt": 100,
          "desc": "foo"
        }
      }
    },
    {
      "request": {
        "url": "/api/core-test/1",
        "method": "PUT",
        "headers": {
          "Content-Type": "%{$[0].headers.Content-Type[0]}"
        },
        "body": {
          "flag": false,
          "amt": "%{$[0].body.amt}",
          "desc": "%{$[0].body.desc}"
        }
      },
      "response": {
        "status": 201,
        "body": {
          "flag": false,
          "amt": 100,
          "desc": "foo"
        }
      }
    }
  ],
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/xml/AssertPostXml.json
{
  "metadata": {
    "name": "Assert post to amqp mock",
    "description": "Assert post to amqp mock"
  },
  "setup": {
  },
  "request": {
    "url": "/createXml",
    "method": "POST",
    "headers": {
      "Content-Type": "application/xml"
    },
    "body": "<foo><bar/></foo>"
  },
  "response": {
    "status": 201,
    "headers": {
      "Content-Type": "application/xml;charset=UTF-8"
    },
    "body": "<foo><bar/></foo>"
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/AssertPath.json
{
  "metadata": {
    "name": "Assert path",
    "description": "Assert path",
    "assert": {
      "ignore": [
        "id"
      ]
    }
  },
  "setup": {
  },
  "scenario": [
    {
      "request": {
        "url": "/echo",
        "method": "POST",
        "path": [
          "foobar",
          "hoge"
        ]
      },
      "response": {
        "status": 200,
        "body": {
          "message": "foobar",
          "note": "hoge"
        }
      }
    },
    {
      "request": {
        "url": "/echo",
        "method": "GET",
        "path": [
          "%{$[0].body.id}"
        ]
      },
      "response": {
        "status": 200,
        "body": {
          "message": "foobar",
          "note": "hoge"
        }
      }
    }
  ],
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/text/AssertTextHtml.json
{
  "metadata": {
    "name": "Assert HTML",
    "description": "Assert HTML"
  },
  "setup": {
  },
  "request": {
    "url": "/text/html",
    "method": "GET",
    "headers": {
      "Accept": "text/html"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "text/html;charset=UTF-8"
    },
    "body": "<html><body><div>Hello html in Spring Boot Integration Test Framework.</div></body></html>"
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/injection/AssertDynamicValueInjection.json
{
  "metadata": {
    "name": "Assert dynamic value injection",
    "description": "Assert dynamic value injection",
    "assert": {
      "body": "IGNORE"
    },
    "properties": {
      "$ref": "integration/variables/dynamicProperties.json/#/"
    }
  },
  "setup": {
  },
  "request": {
    "url": "/api/core-test",
    "method": "POST",
    "headers": {
      "uuid": "```uuid()```",
      "token": {
        "$ref": "#/messageDigest"
      }
    },
    "body": {
      "flag": {
        "$ref": "#/randomBoolean"
      },
      "amt": {
        "$ref": "#/squaring"
      },
      "desc": {
        "$ref": "#/urlEncode"
      }
    }
  },
  "response": {
    "status": 201
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/text/AssertXhtml.json
{
  "metadata": {
    "name": "Assert Xhtml",
    "description": "Assert Xhtml"
  },
  "setup": {
  },
  "request": {
    "url": "/text/xhtml",
    "method": "GET",
    "headers": {
      "Accept": "application/xhtml+xml"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/xhtml+xml;charset=UTF-8"
    },
    "body": "<html><body><div>Hello xhtml in Spring Boot Integration Test Framework.</div></body></html>"
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/xml/support/AssertWireMockNotFound.json
{
  "metadata": {
    "name": "Assert not mocked",
    "description": "Assert not mocked",
    "assert": {
      "header": "REGEX"
    }
  },
  "setup": {
    "wiremock": [
      {
        "request": {
          "url": "/xmlFromExternal/2",
          "method": "GET"
        },
        "response": {
          "status": 404,
          "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><message>Not Found</message>"
        }
      }
    ]
  },
  "request": {
    "url": "/getXmlFromExternal/2",
    "method": "GET"
  },
  "response": {
    "status": 404,
    "headers": {
      "Content-Type": "application\/xml;charset=(utf|UTF)-8"
    },
    "body": "<?xml version=\"1.0\" encoding=\"utf-8\"?><message>Not Found</message>"
  },
  "cleanup": {
  }
}
