=== gajarajkalburgi/spring-integration/core/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "assert": {
          "type": "object",
          "properties": {
            "body": {
              "enum" : ["EQUALS","SCHEMA","IGNORE","REGEX"]
            },
            "header": {
              "enum" : ["EQUALS","REGEX"]
            },
            "ignore": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            },
            "order": {
              "type": "boolean"
            },
            "swagger": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "properties": {
          "type": "object"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "description"
      ]
    },
    "setup": {
      "type": "object",
      "properties": {
        "database": {
          "type": ["object", "array"]
        },
        "wiremock": {
          "type": ["object", "array"]
        },
        "mongodb": {
          "type": ["object", "array"]
        },
        "amqp": {
          "type": ["object", "array"],
          "properties": {
            "queue": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "exclusive": {
                  "type": "boolean",
                  "default": false
                },
                "autoDelete": {
                  "type": "boolean",
                  "default": false
                },
                "arguments": {
                  "type": "object"
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            },
            "exchange": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "type": {
                  "enum": ["direct", "fanout", "topic", "headers", "DIRECT", "FANOUT", "TOPIC", "HEADERS"],
                  "default": "fanout"
                },
                "routingKey": {
                  "type": "string"
                },
                "autoDelete": {
                  "type": "boolean",
                  "default": false
                },
                "arguments": {
                  "type": "object"
                },
                "headers": {
                  "type": ["object", "string", "array"]
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            },
            "messages": {
              "type": ["object", "string", "array"]
            }
          },
          "additionalProperties": false,
          "required": ["queue", "exchange"]
        }
      },
      "additionalProperties": false
    },
    "request": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "minLength": 1
        },
        "method": {
          "enum": ["GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"]
        },
        "headers": {
          "type": ["object", "string"]
        },
        "body": {
          "type": ["object", "array", "string", "null"]
        },
        "query": {
          "type": ["object", "null"]
        },
        "path": {
          "type": ["array", "null"]
        }
      },
      "additionalProperties": false,
      "required": [
        "url",
        "method"
      ]
    },
    "response": {
      "type": "object",
      "properties": {
        "status": {
          "type": "number",
          "minimum": 200,
          "maximum": 510
        },
        "headers": {
          "type": ["object","string"]
        },
        "body": {
          "type": ["object", "array", "string", "null", "boolean", "integer", "number"]
        }
      },
      "additionalProperties": false,
      "required": [
        "status"
      ]
    },
    "scenario": {
      "type": "array",
      "properties": {
        "request": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "minLength": 1
            },
            "method": {
              "enum": ["GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"]
            },
            "headers": {
              "type": ["object", "string"]
            },
            "body": {
              "type": ["object", "array", "string", "null"]
            }
          },
          "additionalProperties": false,
          "required": [
            "url",
            "method"
          ]
        },
        "response": {
          "type": "object",
          "properties": {
            "status": {
              "type": "number",
              "minimum": 200,
              "maximum": 510
            },
            "headers": {
              "type": ["object","string"]
            },
            "body": {
              "type": ["object", "array", "string", "null", "boolean", "integer", "number"]
            }
          },
          "additionalProperties": false,
          "required": [
            "request",
            "response"
          ]
        }
      }
    },
    "cleanup": {
      "type": "object",
      "properties": {
        "database": {
          "type": ["object", "array"]
        },
        "mongodb": {
          "type": ["object", "array"]
        },
        "amqp": {
          "type": ["object", "array"],
          "properties": {
            "queue": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            },
            "exchange": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "oneOf" : [
    {
      "required": [
        "metadata",
        "request",
        "response"
      ]
    },
    {
      "required": [
        "metadata",
        "scenario"
      ]
    }
  ]
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/injection/AssertFileContentsInjection.json
{
  "metadata": {
    "name": "Assert wire mock",
    "description": "Assert wire mock",
    "properties": {
      "flag": "```randomBoolean()```",
      "amt": "```randomInt(8000, 12000)```",
      "desc": "```urlEncode('説明文ディスクリプション')```"
    }
  },
  "setup": {
    "wiremock": {
      "$ref": "integration/variables/external.json/#/"
    }
  },
  "request": {
    "url": "/coreTestsWithExternal/1",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
      "flag": {
        "$ref": "#/flag"
      },
      "amt": {
        "$ref": "#/amt"
      },
      "desc": {
        "$ref": "#/desc"
      }
    }
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/media/AssertGifImage.json
{
  "metadata": {
    "name": "Assert png image",
    "description": "Assert png image"
  },
  "setup": {
  },
  "request": {
    "url": "/media/",
    "method": "GET",
    "headers": {
      "Accept": "image/gif"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "image/gif"
    },
    "body": "@media/running.gif"
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/AssertPathAndQuery.json
{
  "metadata": {
    "name": "Assert path and query",
    "description": "Assert with request which has path and query"
  },
  "setup": {
    "wiremock": [
      {
        "request": {
          "method": "GET",
          "url": "/external/bookIds"
        },
        "response": {
          "status": 200,
          "jsonBody": [
            12578,
            86465,
            99009
          ]
        }
      }
    ]
  },
  "scenario": [
    {
      "request": {
        "url": "/coreTestsWithExternal/bookIds",
        "method": "GET"
      },
      "response": {
        "status": 200,
        "body": [
          12578,
          86465,
          99009
        ]
      }
    },
    {
      "request": {
        "url": "/",
        "method": "GET",
        "path": [
          "findBookById"
        ],
        "query": {
          "id": "%{$[0].body[0]}"
        }
      },
      "response": {
        "status": 200,
        "body": {
          "author": "Giada De Laurentiis",
          "category": "COOKING",
          "reservation": true,
          "id": 12578,
          "title": "Everyday Italian",
          "year": "2005",
          "price": 30.0
        }
      }
    }
  ],
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/support/AssertWireMock.json
{
  "metadata": {
    "name": "Assert wire mock",
    "description": "Assert wire mock",
    "properties": {
      "flag": true,
      "amt": 1000,
      "desc": "説明文ディスクリプション"
    }
  },
  "setup": {
    "wiremock": {
      "$ref": "integration/variables/wiremockTest.json/#/"
    }
  },
  "request": {
    "url": "/coreTestsWithExternal/1",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
      "flag": {
        "$ref": "#/flag"
      },
      "amt": {
        "$ref": "#/amt"
      },
      "desc": {
        "$ref": "#/desc"
      }
    }
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/xml/AssertHeaderRegex.json
{
  "metadata": {
    "name": "Assert header regex",
    "description": "Assert header regex",
    "assert": {
      "body": "IGNORE",
      "header": "REGEX"
    }
  },
  "setup": {
  },
  "request": {
    "url": "/bookStore",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "headers": {
      "content-type": "^application/xml$"
    }
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/injection/AssertValueReference.json
{
  "metadata": {
    "name": "Assert value reference",
    "description": "Assert value reference",
    "assert": {
      "header": "REGEX",
      "ignore": [
        "$._links"
      ]
    },
    "properties": {
      "obj": {
        "flag": false,
        "amt": [
          16,
          32,
          64,
          128
        ],
        "sub": {
          "desc": "```urlEncode('説明文ディスクリプション')```"
        }
      }
    }
  },
  "setup": {
  },
  "request": {
    "url": "/api/core-test",
    "method": "POST",
    "body": {
      "flag": {
        "$ref": "#/obj/flag"
      },
      "amt": {
        "$ref": "#/obj/amt/3"
      },
      "desc": {
        "$ref": "#/obj/sub/desc"
      }
    }
  },
  "response": {
    "status": 201,
    "headers": {
      "Content-Type": {
        "$ref": "integration/constant.json/#/contentType/applicationJson"
      }
    },
    "body": {
      "flag": {
        "$ref": "#/obj/flag"
      },
      "amt": {
        "$ref": "#/obj/amt/3"
      },
      "desc": {
        "$ref": "#/obj/sub/desc"
      }
    }
  },
  "cleanup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query2"
      }
    ]
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/AssertBodySchema.json
{
  "metadata": {
    "name": "Assert body schema",
    "description": "Assert body schema",
    "assert": {
      "body": "SCHEMA"
    }
  },
  "setup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query1"
      }
    ]
  },
  "request": {
    "url": "/api/core-test/1",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
      "flag": {
        "type": "boolean",
        "enum": [
          true
        ]
      },
      "amt": {
        "type": "number"
      },
      "desc": {
        "type": "string",
        "pattern": "[a-z]+"
      }
    }
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/xml/AssertNotFound.json
{
  "metadata": {
    "name": "Assert not found",
    "description": "Assert not found",
    "assert": {
      "header": "REGEX",
      "body": "IGNORE"
    }
  },
  "setup": {
  },
  "request": {
    "url": "/bookStore/dummy/",
    "method": "GET"
  },
  "response": {
    "status": 404,
    "headers": {
      "Content-Type": {
        "$ref": "integration/constant.json/#/contentType/applicationJson"
      }
    }
  },
  "cleanup": {
  }
}
