=== gajarajkalburgi/spring-integration/core/src/main/resources/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "type": "object",
  "properties": {
    "metadata": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "minLength": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "assert": {
          "type": "object",
          "properties": {
            "body": {
              "enum" : ["EQUALS","SCHEMA","IGNORE","REGEX"]
            },
            "header": {
              "enum" : ["EQUALS","REGEX"]
            },
            "ignore": {
              "type": "array",
              "items": {
                "type": "string",
                "minLength": 1
              }
            },
            "order": {
              "type": "boolean"
            },
            "swagger": {
              "type": "string",
              "format": "uri"
            }
          },
          "additionalProperties": false
        },
        "properties": {
          "type": "object"
        }
      },
      "additionalProperties": false,
      "required": [
        "name",
        "description"
      ]
    },
    "setup": {
      "type": "object",
      "properties": {
        "database": {
          "type": ["object", "array"]
        },
        "wiremock": {
          "type": ["object", "array"]
        },
        "mongodb": {
          "type": ["object", "array"]
        },
        "amqp": {
          "type": ["object", "array"],
          "properties": {
            "queue": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "exclusive": {
                  "type": "boolean",
                  "default": false
                },
                "autoDelete": {
                  "type": "boolean",
                  "default": false
                },
                "arguments": {
                  "type": "object"
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            },
            "exchange": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                },
                "type": {
                  "enum": ["direct", "fanout", "topic", "headers", "DIRECT", "FANOUT", "TOPIC", "HEADERS"],
                  "default": "fanout"
                },
                "routingKey": {
                  "type": "string"
                },
                "autoDelete": {
                  "type": "boolean",
                  "default": false
                },
                "arguments": {
                  "type": "object"
                },
                "headers": {
                  "type": ["object", "string", "array"]
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            },
            "messages": {
              "type": ["object", "string", "array"]
            }
          },
          "additionalProperties": false,
          "required": ["queue", "exchange"]
        }
      },
      "additionalProperties": false
    },
    "request": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string",
          "minLength": 1
        },
        "method": {
          "enum": ["GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"]
        },
        "headers": {
          "type": ["object", "string"]
        },
        "body": {
          "type": ["object", "array", "string", "null"]
        },
        "query": {
          "type": ["object", "null"]
        },
        "path": {
          "type": ["array", "null"]
        }
      },
      "additionalProperties": false,
      "required": [
        "url",
        "method"
      ]
    },
    "response": {
      "type": "object",
      "properties": {
        "status": {
          "type": "number",
          "minimum": 200,
          "maximum": 510
        },
        "headers": {
          "type": ["object","string"]
        },
        "body": {
          "type": ["object", "array", "string", "null", "boolean", "integer", "number"]
        }
      },
      "additionalProperties": false,
      "required": [
        "status"
      ]
    },
    "scenario": {
      "type": "array",
      "properties": {
        "request": {
          "type": "object",
          "properties": {
            "url": {
              "type": "string",
              "minLength": 1
            },
            "method": {
              "enum": ["GET", "HEAD", "POST", "PUT", "DELETE", "CONNECT", "OPTIONS", "TRACE", "PATCH"]
            },
            "headers": {
              "type": ["object", "string"]
            },
            "body": {
              "type": ["object", "array", "string", "null"]
            }
          },
          "additionalProperties": false,
          "required": [
            "url",
            "method"
          ]
        },
        "response": {
          "type": "object",
          "properties": {
            "status": {
              "type": "number",
              "minimum": 200,
              "maximum": 510
            },
            "headers": {
              "type": ["object","string"]
            },
            "body": {
              "type": ["object", "array", "string", "null", "boolean", "integer", "number"]
            }
          },
          "additionalProperties": false,
          "required": [
            "request",
            "response"
          ]
        }
      }
    },
    "cleanup": {
      "type": "object",
      "properties": {
        "database": {
          "type": ["object", "array"]
        },
        "mongodb": {
          "type": ["object", "array"]
        },
        "amqp": {
          "type": ["object", "array"],
          "properties": {
            "queue": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": false,
              "required": [
                "name"
              ]
            },
            "exchange": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string",
                  "minLength": 1
                }
              },
              "additionalProperties": false,
              "required": ["name"]
            }
          },
          "additionalProperties": false
        }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false,
  "oneOf" : [
    {
      "required": [
        "metadata",
        "request",
        "response"
      ]
    },
    {
      "required": [
        "metadata",
        "scenario"
      ]
    }
  ]
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/support/AssertWireMockWithQueryString.json
{
  "metadata": {
    "name": "Assert wire mock with query string",
    "description": "Assert wire mock with query string"
  },
  "setup": {
    "wiremock": [
      {
        "request": {
          "method": "GET",
          "url": "/external/findBy?year=2017&month=10&day=7&time=19:00"
        },
        "response": {
          "status": 200,
          "jsonBody": {
            "result": "FOUND"
          }
        }
      }
    ]
  },
  "request": {
    "url": "/wiremockWithQuery",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
      "result": "FOUND"
    }
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/ignore/AssertPartialIgnore.json
{
  "metadata": {
    "name": "Assert ignore",
    "description": "Assert ignore",
    "assert": {
      "ignore": [
        "$._links"
      ]
    }
  },
  "setup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query1"
      }
    ]
  },
  "request": {
    "url": "/api/core-test/1",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
      "flag": true,
      "amt": 100,
      "desc": "foo"
    }
  },
  "cleanup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query2"
      }
    ]
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/support/AssertWireMockWithRegex.json
{
  "metadata": {
    "name": "Assert wire mock with regex",
    "description": "Assert wire mock with regex"
  },
  "setup": {
    "wiremock": [
      {
        "request" : {
          "urlPattern" : "/maps/api/timezone/json\\?key=(\\w+)&location=35\\.01412100%2C135\\.67659200&timestamp=(\\d+)",
          "method" : "GET"
        },
        "response" : {
          "status" : 200,
          "headers" : {
            "content-type" : "application/json;charset=UTF-8"
          },
          "jsonBody" : {
            "dstOffset" : 0,
            "rawOffset" : 10800,
            "status" : "OK",
            "timeZoneId" : "Europe/Istanbul",
            "timeZoneName" : "GMT+03:00"
          }
        }
      }
    ]
  },
  "request": {
    "url": "/wiremockWithRegex?key=foobar&timestamp=1512111317999",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
      "dstOffset" : 0,
      "rawOffset" : 10800,
      "status" : "OK",
      "timeZoneId" : "Europe/Istanbul",
      "timeZoneName" : "GMT+03:00"
    }
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/ignore/AssertBodyIgnore.json
{
  "metadata": {
    "name": "Assert body ignore",
    "description": "Assert body ignore",
    "assert": {
      "body": "IGNORE"
    }
  },
  "setup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query1"
      }
    ]
  },
  "request": {
    "url": "/api/core-test/1",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "body": {
    }
  },
  "cleanup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query2"
      }
    ]
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/AssertMultiPart.json
{
  "metadata": {
    "name": "Assert multi part",
    "description": "Assert multi part",
    "assert": {
      "order": false
    }
  },
  "setup": {
  },
  "request": {
    "url": "/upload/",
    "method": "POST",
    "headers": {
      "Accept": "*/*",
      "Content-Type": "multipart/form-data"
    },
    "body": {
      "media": "@integration/image/spring-boot.png",
      "stringValue": "This is Spring Boot logo.",
      "metadata": {
        "url": "https://spring.io/"
      }
    }
  },
  "response": {
    "status": 200,
    "body": [
      "media",
      "stringValue",
      "metadata"
    ]
  },
  "cleanup": {}
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/json/ignore/AssertIgnoreArrayOrder.json
{
  "metadata": {
    "name": "Assert ignore array order",
    "description": "Assert ignore array order",
    "assert": {
      "header": "REGEX",
      "ignore": [
        "$.._links"
      ],
      "order": false
    }
  },
  "setup": {
    "database": [
      "INSERT INTO CORE_TEST (ID, FLAG, AMT, DESC) VALUES ('1', true, 100 ,'foo')",
      "INSERT INTO CORE_TEST (ID, FLAG, AMT, DESC) VALUES ('2', false, 500 ,'bar')"
    ]
  },
  "request": {
    "url": "/api/core-test",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": {
        "$ref": "integration/constant.json/#/contentType/applicationJson"
      }
    },
    "body": {
      "_embedded": {
        "coreTests": [
          {
            "flag": false,
            "amt": 500,
            "desc": "bar"
          },
          {
            "flag": true,
            "amt": 100,
            "desc": "foo"
          }
        ]
      }
    }
  },
  "cleanup": {
    "database": [
      {
        "$ref": "integration/variables/objective.json/#/query2"
      }
    ]
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/text/AssertSimleText.json
{
  "metadata": {
    "name": "Assert Simple Text",
    "description": "Assert Simple Text"
  },
  "setup": {
  },
  "request": {
    "url": "/text/simpletext",
    "method": "GET"
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "text/plain;charset=UTF-8"
    },
    "body": "Hello simpletext in Spring Boot Integration Test Framework."
  },
  "cleanup": {
  }
}

=== gajarajkalburgi/spring-integration/tests/src/test/resources/integration/test/text/AssertRegex.json
{
  "metadata": {
    "name": "Assert REGEX",
    "description": "Assert REGEX",
    "assert": {
      "body": "REGEX"
    }
  },
  "setup": {
  },
  "request": {
    "url": "/text/xhtml",
    "method": "GET",
    "headers": {
      "Accept": "application/xhtml+xml"
    }
  },
  "response": {
    "status": 200,
    "headers": {
      "Content-Type": "application/xhtml+xml;charset=UTF-8"
    },
    "body": "<html><body><div>Hello .* in Spring Boot Integration Test Framework\\.</div></body></html>"
  },
  "cleanup": {
  }
}
